### ISSUE TITLE
你好，我使用后 提示报错了

### ISSUE THREAD

**Issue by Smecta** [Taogram/taobi#7]
![CleanShot 2024-07-18 at 12 37 00@2x](https://github.com/user-attachments/assets/4e16e893-c417-47da-8cd1-32b17c57adbd)
两个报错，能给解决一下吗
`
[Vue warn]: Error in mounted hook: "TypeError: Julian.DT$JD is not a function"

found in

---> <About> at src/views/home/about.vue
       <AppLayout> at src/views/layouts/index.vue
         <App> at src/App.vue
           <Root>

TypeError: Julian.DT$JD is not a function
    at SolarTerms.getBaseSection (solarTerms.js:25:1)
    at SolarTerms.getSolarTerms (solarTerms.js:33:1)
    at solarTerms.js:45:1
    at Array.map (<anonymous>)
    at SolarTerms.getSolarTermsAll (solarTerms.js:44:1)
    at Calendar.algorithm (SolarCalendar.js:37:1)
    at new Calendar (Calendar.js:57:1)
    at #generateCalendar (TheArtOfBecomingInvisible.js:56:1)
    at new TheArtOfBecomingInvisible (TheArtOfBecomingInvisible.js:31:1)
    at VueComponent.initData (about.vue:25:1)
`

**Comment by laxnogithub** [comment]
可能是没打包成前端版本的，我测试下看看

**Comment by laxnogithub** [comment]
目前已更新了包，是一个内置包版本的问题
